###  Coursera Capstone by **Oluwasen Mesele** 

####  This Notebook will contain code for capstone project

In [82]:
import pandas as pd
import numpy as np

print('Hello Capstone Project Course!')

Hello Capstone Project Course!

In [3]:
!pip install lxml html5lib beautifulsoup4

Requirement already satisfied: lxml in /Users/oluwaseunmesele/opt/anaconda3/lib/python3.8/site-packages (4.6.1)
Requirement already satisfied: html5lib in /Users/oluwaseunmesele/opt/anaconda3/lib/python3.8/site-packages (1.1)
Requirement already satisfied: beautifulsoup4 in /Users/oluwaseunmesele/opt/anaconda3/lib/python3.8/site-packages (4.9.3)
Requirement already satisfied: six>=1.9 in /Users/oluwaseunmesele/opt/anaconda3/lib/python3.8/site-packages (from html5lib) (1.15.0)
Requirement already satisfied: webencodings in /Users/oluwaseunmesele/opt/anaconda3/lib/python3.8/site-packages (from html5lib) (0.5.1)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in /Users/oluwaseunmesele/opt/anaconda3/lib/python3.8/site-packages (from beautifulsoup4) (2.0.1)

#### Scrape Wikipedia page in order to obtain the data that is the table of postal codes in Toronto, CA and to transform the data into a pandas  dataframe

In [83]:
#import table and print number of tables
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
dfs = pd.read_html(url)

print(len(dfs))

3

In [84]:
#check first table. Looks like table we want

dfs[0].head()

  Postal Code           Borough              Neighbourhood
0         M1A      Not assigned               Not assigned
1         M2A      Not assigned               Not assigned
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

In [85]:

#set 1st table as canada_df and then drop rows where borough is n ot assigned

canada_df = dfs[0]



canada_df = canada_df[canada_df['Borough'] != 'Not assigned']

canada_df.reset_index(inplace = True, drop=True)
canada_df.head()

  Postal Code           Borough                                Neighbourhood
0         M3A        North York                                    Parkwoods
1         M4A        North York                             Victoria Village
2         M5A  Downtown Toronto                    Regent Park, Harbourfront
3         M6A        North York             Lawrence Manor, Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [86]:
#combine rows by postal codes, for all neighborhoods within the postal code
canada_df = canada_df.groupby('Postal Code', as_index=False).agg(','.join)
canada_df.head(30)

   Postal Code      Borough                                      Neighbourhood
0          M1B  Scarborough                                     Malvern, Rouge
1          M1C  Scarborough             Rouge Hill, Port Union, Highland Creek
2          M1E  Scarborough                  Guildwood, Morningside, West Hill
3          M1G  Scarborough                                             Woburn
4          M1H  Scarborough                                          Cedarbrae
5          M1J  Scarborough                                Scarborough Village
6          M1K  Scarborough        Kennedy Park, Ionview, East Birchmount Park
7          M1L  Scarborough                    Golden Mile, Clairlea, Oakridge
8          M1M  Scarborough    Cliffside, Cliffcrest, Scarborough Village West
9          M1N  Scarborough                        Birch Cliff, Cliffside West
10         M1P  Scarborough  Dorset Park, Wexford Heights, Scarborough Town...
11         M1R  Scarborough                                  Wexford, Maryvale
12         M1S  Scarborough                                          Agincourt
13         M1T  Scarborough            Clarks Corners, Tam O'Shanter, Sullivan
14         M1V  Scarborough  Milliken, Agincourt North, Steeles East, L'Amo...
15         M1W  Scarborough                      Steeles West, L'Amoreaux West
16         M1X  Scarborough                                        Upper Rouge
17         M2H   North York                                  Hillcrest Village
18         M2J   North York                       Fairview, Henry Farm, Oriole
19         M2K   North York                                    Bayview Village
20         M2L   North York                           York Mills, Silver Hills
21         M2M   North York                            Willowdale, Newtonbrook
22         M2N   North York                        Willowdale, Willowdale East
23         M2P   North York                                    York Mills West
24         M2R   North York                        Willowdale, Willowdale West
25         M3A   North York                                          Parkwoods
26         M3B   North York                                          Don Mills
27         M3C   North York                                          Don Mills
28         M3H   North York    Bathurst Manor, Wilson Heights, Downsview North
29         M3J   North York                    Northwood Park, York University

In [87]:
##determine if there are non assigned neighborhoods and then change the neighbourhood to the borough
print(canada_df[canada_df['Neighbourhood'] == 'Not Assigned'])

for idx, row in canada_df.iterrows():
    if row['Neighbourhood'] == 'Not Assigned':
        row['Neighbourhood'] = row['Borough']
canada_df.head()
canada_df.shape

Empty DataFrame
Columns: [Postal Code, Borough, Neighbourhood]
Index: []

(103, 3)